const POSTS = [
  {
    id: '1',
    slug: 'social-media-automation-guide',
    title: '10 Social Media Automation Strategies to Save 10 Hours a Week',
    excerpt: 'Discover powerful automation techniques that streamline your social media marketing while maintaining authentic engagement with your audience.',
    content:
      'Social media automation doesn\'t mean losing the human touch. Learn how to automate scheduling, content curation, and engagement tracking while keeping your brand voice authentic. This comprehensive guide covers tools, best practices, and real-world examples from successful marketers who\'ve reduced their social media workload by 80%.',
    date: '2025-11-08',
    author: 'Sarah Johnson',
    tags: ['automation', 'social-media', 'productivity'],
    views: 3245,
    likes: 587,
    featuredImage: '/techsho.png',
    service: 'social-media-automation',
  },
  {
    id: '2',
    slug: 'marketing-automation-roi',
    title: 'Measuring Marketing Automation ROI: A Complete Framework',
    excerpt: 'Learn how to track, measure, and optimize your marketing automation campaigns to prove real business value and justify your marketing spend.',
    content:
      'Marketing automation is an investment, and like any investment, you need to measure returns. This guide walks through setting up KPIs, attribution models, and dashboards that show exactly how automation drives revenue. Includes templates, formulas, and case studies showing 300%+ ROI improvements.',
    date: '2025-11-05',
    author: 'Michael Chen',
    tags: ['automation', 'analytics', 'roi'],
    views: 2890,
    likes: 421,
    featuredImage: '/iphone15progray.jpg',
    service: 'marketing-automation',
  },
  {
    id: '3',
    slug: 'chatbot-marketing-strategies',
    title: 'Chatbot Marketing: Converting Visitors into Customers 24/7',
    excerpt: 'How AI-powered chatbots can qualify leads, answer questions, and drive conversions even when your sales team is offline.',
    content:
      'Chatbots have evolved from simple FAQ responders to sophisticated sales assistants. Learn how to design conversation flows that feel natural, integrate with your CRM, and hand off seamlessly to human agents. Real examples show 45% increase in qualified leads and 60% faster response times.',
    date: '2025-11-02',
    author: 'Emily Rodriguez',
    tags: ['chatbot', 'ai', 'conversion'],
    views: 4120,
    likes: 892,
    featuredImage: '/signinlog.png',
    service: 'chatbot-marketing',
  },
  {
    id: '4',
    slug: 'email-automation-workflows',
    title: 'Email Automation Workflows That Drive 40% More Revenue',
    excerpt: 'Build sophisticated email sequences that nurture leads, recover abandoned carts, and re-engage dormant customers automatically.',
    content:
      'Email automation is more than welcome messages. Discover advanced workflows for onboarding, cart abandonment, win-back campaigns, and post-purchase nurturing. Includes trigger optimization, timing best practices, and A/B testing strategies that top e-commerce brands use to maximize lifetime value.',
    date: '2025-10-30',
    author: 'David Park',
    tags: ['email', 'automation', 'workflows'],
    views: 3567,
    likes: 654,
    featuredImage: '/logo.png',
    service: 'email-automation',
  },
  {
    id: '5',
    slug: 'facebook-messenger-automation',
    title: 'Facebook Messenger Automation: The Ultimate Guide for 2025',
    excerpt: 'Harness the power of Messenger automation to engage customers where they spend most of their time - on Facebook.',
    content:
      'With 1.3 billion monthly users, Facebook Messenger is a goldmine for customer engagement. Learn how to build automated sequences for lead generation, customer support, and sales. Covers ManyChat integration, compliance best practices, and proven templates that achieve 80%+ open rates.',
    date: '2025-10-28',
    author: 'Jessica Liu',
    tags: ['messenger', 'facebook', 'automation'],
    views: 2934,
    likes: 511,
    featuredImage: '/techsho.png',
    service: 'messenger-automation',
  },
  {
    id: '6',
    slug: 'instagram-marketing-automation',
    title: 'Instagram Marketing Automation: Grow Your Following Organically',
    excerpt: 'Automate your Instagram strategy without sacrificing authenticity. Proven tactics to increase engagement and followers.',
    content:
      'Instagram automation requires a delicate balance. This guide shows you how to automate content scheduling, story posting, DM responses, and engagement activities while staying within platform guidelines. Includes growth hacking techniques that helped brands gain 10K+ followers in 90 days.',
    date: '2025-10-25',
    author: 'Alex Thompson',
    tags: ['instagram', 'automation', 'growth'],
    views: 5210,
    likes: 1023,
    featuredImage: '/iphone15progray.jpg',
    service: 'instagram-automation',
  },
  {
    id: '7',
    slug: 'lead-nurturing-automation',
    title: 'Lead Nurturing Automation: From Stranger to Customer',
    excerpt: 'Design automated nurturing campaigns that educate prospects and move them through your sales funnel effortlessly.',
    content:
      'Not every lead is ready to buy today. Build multi-touch nurturing sequences that deliver value at each stage of the buyer journey. Covers content mapping, scoring systems, and trigger-based personalization that converts 3x more leads than generic broadcasts.',
    date: '2025-10-22',
    author: 'Robert Martinez',
    tags: ['lead-nurturing', 'automation', 'sales'],
    views: 2156,
    likes: 389,
    featuredImage: '/signinlog.png',
    service: 'lead-nurturing',
  },
  {
    id: '8',
    slug: 'sms-marketing-automation',
    title: 'SMS Marketing Automation: Driving Instant Action',
    excerpt: 'With 98% open rates, SMS is the most direct channel. Learn how to automate text campaigns that customers actually want to receive.',
    content:
      'SMS cuts through the noise like no other channel. Discover segmentation strategies, timing optimization, and compliance requirements for successful SMS automation. Includes flash sale alerts, appointment reminders, and delivery updates that achieve 45% CTR.',
    date: '2025-10-20',
    author: 'Nina Patel',
    tags: ['sms', 'automation', 'mobile'],
    views: 1876,
    likes: 298,
    featuredImage: '/logo.png',
    service: 'sms-automation',
  },
  {
    id: '9',
    slug: 'multi-channel-marketing-automation',
    title: 'Multi-Channel Marketing Automation: The Omnichannel Approach',
    excerpt: 'Orchestrate seamless customer experiences across email, SMS, social media, and chat with unified automation.',
    content:
      'Customers interact with your brand across multiple touchpoints. Learn how to create cohesive automation flows that adapt messaging based on channel preferences and behavior. Case studies show how omnichannel approaches increase customer retention by 89%.',
    date: '2025-10-18',
    author: 'Tom Anderson',
    tags: ['multi-channel', 'automation', 'strategy'],
    views: 3421,
    likes: 612,
    featuredImage: '/techsho.png',
    service: 'multi-channel-automation',
  },
  {
    id: '10',
    slug: 'marketing-automation-for-ecommerce',
    title: 'E-commerce Marketing Automation: Boosting Sales on Autopilot',
    excerpt: 'Automate your e-commerce marketing to recover carts, upsell customers, and build loyalty without lifting a finger.',
    content:
      'E-commerce automation goes beyond abandoned cart emails. Explore product recommendation engines, browse abandonment flows, post-purchase sequences, and win-back campaigns. Includes Shopify, WooCommerce, and Magento integration guides with revenue-driving templates.',
    date: '2025-10-15',
    author: 'Lisa Wang',
    tags: ['ecommerce', 'automation', 'sales'],
    views: 4567,
    likes: 834,
    featuredImage: '/iphone15progray.jpg',
    service: 'ecommerce-automation',
  },
  {
    id: '11',
    slug: 'customer-engagement-automation',
    title: 'Customer Engagement Automation: Building Lasting Relationships',
    excerpt: 'Keep customers engaged with personalized, automated touchpoints that feel human and drive loyalty.',
    content:
      'Engagement doesn\'t end at purchase. Build automated journeys for onboarding, milestone celebrations, feedback collection, and loyalty rewards. Learn how to use behavioral triggers and preference centers to deliver perfectly timed messages that customers love.',
    date: '2025-10-12',
    author: 'Chris Brown',
    tags: ['engagement', 'automation', 'loyalty'],
    views: 2743,
    likes: 476,
    featuredImage: '/signinlog.png',
    service: 'engagement-automation',
  },
  {
    id: '12',
    slug: 'marketing-automation-best-practices',
    title: 'Marketing Automation Best Practices: Avoiding Common Pitfalls',
    excerpt: 'Learn from the mistakes others have made. Essential do\'s and don\'ts for marketing automation success.',
    content:
      'Marketing automation can backfire when done wrong. Discover the top 15 mistakes marketers make and how to avoid them. Covers over-automation, poor segmentation, neglecting testing, and ignoring data privacy. Plus, a checklist to audit your current automation setup.',
    date: '2025-10-10',
    author: 'Jennifer Lee',
    tags: ['best-practices', 'automation', 'strategy'],
    views: 3892,
    likes: 721,
    featuredImage: '/logo.png',
    service: 'automation-best-practices',
  }
]

export default POSTS
